export enum Collection_Names_Enum {
    ERROR_LOG = 'errorLog',
    USERS = 'users',
    ROLES = 'roles',
    ASSETS = 'assets',
    CREW = 'crew',
    ASSET_CREW = 'assetCrew',
    ASSET_LOCATION = 'assetLocation',
    GEO_FENCES = 'geoFences',
    CREW_LOGIN_LOG = "crewLoginLog",
    SCOPE_AREA = 'workScopeAreas',
    LAYERS = 'layers',
    ENTITY = 'entity',
    CLIENT = 'client',
    OPERATOR = 'operator',
    DETECTION_TYPES = 'DetectionsTypes',
    CASES = 'cases',
    caseConfig = 'caseConfig',
    SEVERITY = "Severity",
    CASE_STATUS = 'CaseStatus',
    Detection = 'Detections',
    DETECTIONS_TYPES = 'DetectionTypes',
    DETECTION_CONFIG = 'DetectionConfig',
    ALERT = 'Alert',
    CONFIDENCE_LEVEL = 'ConfidenceLevel',
    SECTOR = 'Sector',
}